### add message
POST http://localhost:8000/
Content-Type: application/json

{
  "name": "Yvan",
  "message": "some text for test messages"
}


###


GET http://localhost:8000/
Content-Type: text/csv

###

